@startuml システム構成

actor 部員
agent Slack

node ゲートウェイ

node 認証ウェブ
node カレンダーウェブ

node 認証API
node カレンダーAPI
node 通知API

database データベース {
  storage ホワイトリスト
  storage 集会データ
}

部員 -- ゲートウェイ

ゲートウェイ --> 認証ウェブ
認証ウェブ -(0- 認証API
認証API -0)- ホワイトリスト

ゲートウェイ --> カレンダーウェブ
カレンダーウェブ -(0- カレンダーAPI
カレンダーAPI -0)- 集会データ

Slack -(0- 通知API 
通知API -0)- 集会データ

@enduml
