@startuml structure

actor 部員
agent 認証API
agent Slackアプリ

node カレンダーウェブ

node カレンダーAPI

database データベース {
  storage 集会データ
}

部員 -- カレンダーウェブ

認証API <-- カレンダーウェブ
カレンダーウェブ -(0- カレンダーAPI
カレンダーAPI -0)- 集会データ

Slackアプリ -(0- カレンダーAPI

@enduml
