name: Lint
on:
  push:
    branches-ignore:
      - master
  pull_request: {}

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install --no-save

      - name: Run linter
        run: npm run lint
